### ISSUE TITLE
Internet Explorer/Edge Error: Object doesn't support this action

### ISSUE THREAD

**Issue by Vheissu** [aurelia/loader-default#10]
Using the latest version of Aurelia framework dependencies as well as the latest beta version of JSPM (including loader) I am seeing an issue when trying to view my Aurelia application in Internet Explorer 11 as well as the new Edge browser in Windows 10.

I followed the instructions of the latest release to reinstall not just update dependencies as well as make the required changes to my config.js (defaultJSExtensions and path wildcard adjustments).

The error itself is: Unhandled promise rejection Error: Object doesn't support this action Error loading http://localhost:9000/dist/app.html!view

Delving deeper into specifics here is the stack trace of the error:
TypeError: Object doesn't support this action
at getCanonicalName (Unknown script code:104:7)
at fetch (Unknown script code:172:13)
at Anonymous function (http://localhost:9000/jspm_packages/system.js:5:5616)
at Anonymous function (http://localhost:9000/jspm_packages/system.js:5:6656)
at Anonymous function (http://localhost:9000/jspm_packages/system.js:5:8752)
at Anonymous function (http://localhost:9000/jspm_packages/system.js:4:3596)
at run (Unknown script code:91:15)
at Anonymous function (Unknown script code:105:11)

My application works in all other browsers (Chrome and Firefox as well as mobile browsers) it is just IE and Edge. My understanding is that this issue was meant to be fixed in the latest release of the loader-default dependency, so it is possible this could be my fault somehow.

I have tried to debug the issue, but with my limited time and understanding, I came up empty handed on this one.

**Comment by EisenbergEffect** [comment]
It should be fixed in the latest patch release. @jdanyow Can you take a look at this?

**Comment by jdanyow** [comment]
It's working for me, I will be updating a machine to Windows 10 soon so that I can test with Edge.  

@Vheissu can you confirm the version of [`loader-default`](https://github.com/aurelia/loader-default) is 0.9.3? 
Couple ways to do this:

1. check the network tab in the developer tools- you should be seeing this:
`.../jspm_packages/github/aurelia/loader-default@0.9.3/...`
2. run `jspm clean` and confirm that no old versions of `loader-default` are hanging around in your `jspm_packages\aurelia` folder.

**Comment by jdanyow** [comment]
**CORRECTION**
The fix is not working- I was using the wrong repo to test.  In a clean copy of the skelly it does not work in IE11.  This is my fault.  https://github.com/aurelia/loader-default/pull/12 will address this.

**Comment by jdanyow** [comment]
fixed in loader-default version 0.9.4

**Comment by Vheissu** [comment]
@jdanyow You sir are a LEGEND. The issue is definitely fixed. Thank you for your hard work and swift resolution of this issue.
