### ISSUE TITLE
Why is in config.js a transpiler defined although the code is transpiler via gulp to ES5 ?

### ISSUE THREAD

**Issue by paulvanbladel** [aurelia/loader-default#11]
I'm a bit confused by the well-known section in config.js.
When i comment out 
```
/*transpiler: "babel",
  babelOptions: {
    "optional": [
      "es7.decorators",
      "es7.classProperties",
      "runtime"
    ]
  },*/
```
... evertything continues to work as expected (at least what I see).
Anyhow, gulp is doing the compile job and points to his own transpiler options.
I would think that the above is only necessary when you let the browser compile ES6 to ES5 ?
Just trying to demystify a bit more these new dependencies.

**Comment by EisenbergEffect** [comment]
Yes, you are correct. The babel options are only needed with in-browser transpilation.
