### ISSUE TITLE
errors in IE11 , IE10 'URLPolyfill' is undefined

### ISSUE THREAD

**Issue by kobiv** [aurelia/loader-default#13]
The app doesnt have any problem in firefox and chrome
but since i updated to the last version of loader-default 0.9.4 the error occurs and app 
isn't loaded 

Unhandled promise rejection ReferenceError: Error loading "github:aurelia/loader-default@0.9.4
'URLPolyfill' is undefined

**Comment by EisenbergEffect** [comment]
@jdanyow Do we still have an issue here?

**Comment by jdanyow** [comment]
@kobiv if you look at the network tab, is `system-polyfills.js` being loaded prior to `/jspm_packages/github/aurelia/loader-default@0.9.4.js`?

**Comment by kobiv** [comment]
/jspm_packages/github/aurelia/loader-default@0.9.4/aurelia-loader-default.js
is the last resource loaded before i get the polyfill error 
system-polyfills is not loaded before

**Comment by jdanyow** [comment]
interesting- can you try this:

In your index.html, change this line:
```html
<script src="jspm_packages/system.js"></script>
```
to:
```html
<script src="jspm_packages/system.src.js"></script>
```

And then check why you're not getting to this line of code:

https://github.com/systemjs/systemjs/blob/0.18.9/dist/system.src.js#L3969-L3970

**Comment by kobiv** [comment]
i see the issue i have in the jspm_packages a version of system.js 0.6.11 
which has the following line 
  document.write(
        '<' + 'script type="text/javascript" src="' + basePath + 'es6-module-loader.js" data-init="upgradeSystemLoader">' + '<' + '/script>'
      );


that has the following line , but it worked in chrome and firefox well

**Comment by kobiv** [comment]
i have update the files but now i get 
Unhandled promise rejection Error: Object doesn't support this action
	Error loading ..//app.html!view

**Comment by KarlDirck** [comment]
I see this error "'URLPolyfill' is undefined" in Safari 5.1.7 (7534.57.2) as well.  Has there been a resolution yet?
Details: 
Unhandled promise rejection 
Error
line: 49
message: "Error loading "github:aurelia/loader-default@0.9.4" at http://localhost:9000/app/jspm_packages/github/aurelia/loader-default@0.9.4.js↵Can't find variable: URLPolyfill"
sourceId: 2105068632
sourceURL: "http://localhost:9000/"
__proto__: Error

**Comment by jdanyow** [comment]
Safari 5.1.7-  are you on windows?

**Comment by KarlDirck** [comment]
Yes, on Windows 10;  From my testing Microsoft Edge has the same issue.

**Comment by jdanyow** [comment]
ok- will look into the windows-10/edge issue, I'll need to update my machine.

In terms of safari on windows, I don't think that's supported by Apple anymore.

**Comment by KarlDirck** [comment]
Thank you.
I know Safari on windows is no longer officially supported, but has provided a quick iOS lite test.  I believe the new MS Edge uses a Webkit fork, which is probably why they both exhibit the same error.

**Comment by vargasj** [comment]
Hi, I was also having this issue but it was because I forgot to update to jspm beta, after I updated and installed everything again it worked ok.

**Comment by EisenbergEffect** [comment]
This will be fixed in the next release. We've found a way to remove the offending code altogether.

**Comment by sparkbuzz** [comment]
I was having the same issue here, and just wondering, @EisenbergEffect, when you say "next release" how far off would that be?

**Comment by EisenbergEffect** [comment]
Hopefully early next week. We've got some repository maintenance we need to do. Once that is done, we'll do the releases.

**Comment by MaartenThomassen** [comment]
I'm also having the same issue. Hoping for a fix soon as this will enable me to debug my typescript code via visual studio!

**Comment by pawelpawlow** [comment]
@EisenbergEffect can you please post an update here once the fix is released.

**Comment by jdanyow** [comment]
The fix was released- have you updated?
Here's the release announcement with a command you can use to update:  http://blog.durandal.io/2015/09/05/aurelia-early-september-release-notes/

**Comment by pawelpawlow** [comment]
Ok, I'll have to update, thank you @jdanyow

**Comment by KarlDirck** [comment]
Thank you for the fix.  This error is resolved.  However, MS Edge does not seem compatible with Aurelia.  The app seems to fail more often than work, requiring excessive refreshes to only occasionally get a view rendered.  Is anyone looking into compatibility with Edge (Win10) and Safari (iOS?)  Many of our users use these browsers, particularly on mobile devices

**Comment by EisenbergEffect** [comment]
There are other issues we are tracking and they are being worked on, yes.

**Comment by KarlDirck** [comment]
Thank you Rob.

**Comment by OutOfTouch** [comment]
I am getting the same error in IE 10 and I just installed Aurelia via jspm today, I am still a noob with all of this stuff still, my simple hello world app works fine in FF and Chrome. Aurelia version is 1.0.3.
Was this error fixed or am I doing something wrong?

**Comment by EisenbergEffect** [comment]
It was fixed a long time ago. What error are you getting?

**Comment by OutOfTouch** [comment]
Error: Error invoking TaskQueue. Check the inner error for details.
------------------------------------------------
inner error: TypeError: Object doesn't support this action
   at createMutationObserver (Unknown script code:383:7)
   at makeRequestFlushFromMutationObserver (Unknown script code:13:5)
   at TaskQueue (Unknown script code:59:7)
   at invoke (Unknown script code:334:7)
   at invoke (Unknown script code:309:7)
   at invoke (Unknown script code:557:9)
   at get (Unknown script code:145:11)
   at get (Unknown script code:488:11)
   at invoke (Unknown script code:354:7)
   at invoke (Unknown script code:309:7) 

Looks like it is at this line in system.src.js:   var hasURL = typeof URLPolyfill != 'undefined' || new URL('test:///').protocol == 'test:';

**Comment by rdelvek** [comment]
I am getting the same error as OutOfTouch in IE10.  Works fine in IE11.

**Comment by OutOfTouch** [comment]
I only have IE 10 to test with and it is not working in 10.

**Comment by rdelvek** [comment]
Found the fix at:  https://github.com/aurelia/documentation/blob/master/English/docs.md

This must have just been updated.  Works for IE9 and 10 now.

**Comment by OutOfTouch** [comment]
The github:polymer/mutationobservers has been deprecated in favor of https://github.com/webcomponents/webcomponentsjs, so I am not sure what this line should be now: `System.import('core-js').then(function() {
    // Imports MutationObserver polyfill
    return System.import('polymer/mutationobservers');`

> Found the fix at: https://github.com/aurelia/documentation/blob/master/English/docs.md
> 
> This must have just been updated. Works for IE9 and 10 now.
