### ISSUE TITLE
undefined interface in typescript definition

### ISSUE THREAD

**Issue by sujesharukil** [aurelia/loader-default#15]
Aurelia-loader-default.d.ts has DefaultLoader class.loadTemplate function return a Promise<TemplateRegistryEntry>. 

TemplateRegistryEntry is showing up as undefined. Don't know where this is defined.

**Comment by stefan505** [comment]
Also, there's two typos namely `Proimise<any>` and `Promse<any[]>`.

**Comment by paulvanbladel** [comment]
would be happy to do a PR for fixing this, but of course the .d.ts file seems to be generated.
How can we help here? Would be nice to get a pointer on how this file is currently generated.

The full file should be: 
```javascript
declare module 'aurelia-loader-default' {
  import { Origin }  from 'aurelia-metadata';
  import { Loader, TemplateRegistryEntry }  from 'aurelia-loader';
  export class DefaultLoader extends Loader {
    constructor();
    loadModule(id: string): Promise<any>;
    loadAllModules(ids: string[]): Promise<any[]>;
    loadTemplate(url: string): Promise<TemplateRegistryEntry>;
    loadText(url: string): Promise<string>;
  }
}
```

**Comment by JeroenVinke** [comment]
There already are PR's for the promise typo's : https://github.com/aurelia/loader-default/pull/14, https://github.com/aurelia/loader-default/pull/19, https://github.com/aurelia/loader-default/pull/18. I think that the wait is for a release of the babel-dts-generator which fixes the return type issue  (https://github.com/YoloDev/babel-dts-generator/pull/26)

**Comment by EisenbergEffect** [comment]
The PRs will be processed today and we'll get a release out asap. Apologies for the delay in this. Hang tight and there will likely be a new release tonight or tomorrow morning.

**Comment by EisenbergEffect** [comment]
Fixed in a previous release.
