### ISSUE TITLE
Browserify Support

### ISSUE THREAD

**Issue by KenPowers** [aurelia/loader-default#2]
This is a detailed recap of the [gitter discussion](https://gitter.im/Aurelia/Discuss?at=54dac40c5ae7f2da6f3de85e).

There are a few things I've thought of so far which need to happen in order for Aurelia to properly support browserify:

1. Modules should be published on npm.
1. Routers need to be able to get references to modules from browserify.
1. Template text should be bundled in with the JavaScript.

# Modules on NPM

Overall this would make Aurelia easier to use with Browserify. I attempted to do a build of the [`skeleton-navigation`][sn] project by installing the dependencies as bower dependencies and using [debowerify](https://github.com/eugeneware/debowerify) to resolve the bower packages from browserify. Unfortunately this leads to some errors which would require restructuring the bower packages:

```text
Error: Cannot find module './../../../aurelia-dependency-injection/aurelia-dependency-injection.js' from '/Users/kpowers/Downloads/skeleton-navigation/bower_components/aurelia-router/dist/es6'
```

I did get the build working by copying all of the bower packages to the `node_modules` directory.

# Routers

I think it would be beneficial for routers to support a `module` option in addition to the `moduleId` option. To borrow from the [`skeleton-navigation`][sn] project again, the following:

```es6
import {Router} from 'aurelia-router';

export class App {
  static inject() { return [Router]; }
  constructor(router) {
    this.router = router;
    this.router.configure(config => {
      config.title = 'Aurelia';
      config.map([
        { route: ['','welcome'],  moduleId: 'welcome',      nav: true, title:'Welcome' },
        { route: 'flickr',        moduleId: 'flickr',       nav: true },
        { route: 'child-router',  moduleId: 'child-router', nav: true, title:'Child Router' }
      ]);
    });
  }
}
```

Could become the following:

```es6
import {Router} from 'aurelia-router';
import welcome from './welcome';
import flickr from './flickr';
import childRouter from './child-router';

export class App {
  static inject() { return [Router]; }
  constructor(router) {
    this.router = router;
    this.router.configure(config => {
      config.title = 'Aurelia';
      config.map([
        { route: ['','welcome'],  module: welcome,      nav: true, title:'Welcome' },
        { route: 'flickr',        module: flickr,       nav: true },
        { route: 'child-router',  module: childRouter,  nav: true, title:'Child Router' }
      ]);
    });
  }
}
```

This undoes some of the automagic done by Aurelia, but I don't believe this would be a burdensome requirement for using browserify. Users of browserify are already used to creating bundles from single entry points which `require` the modules they need.

# Template Text

Using something like [`brfs`](https://github.com/substack/brfs) or [`html-minifyify`](https://github.com/kesla/html-minifyify) we could support the following:

```es6
import {Behavior} from 'aurelia-framework';
import fs from 'fs';

export class NavBar {
  static get template() {
    return fs.readFileSync(__dirname + '/robot.html', 'utf8');
  }
  static metadata() {
    return Behavior.withProperty('router');
  }
}
```

Now the template text is bundled with the JavaScript rather than imported into the page using `link`s.

[sn]: https://github.com/aurelia/skeleton-navigation "skeleton-navigation"

**Comment by EisenbergEffect** [comment]
Closing this for now. We would be happy to see the community work on this if there's interest.
