### ISSUE TITLE
loadTemplate not working for ie11

### ISSUE THREAD

**Issue by salminio** [aurelia/loader-default#22]
I'm trying to use 

    DefaultLoader.loadTemplate("mypath/myfile.html");

and grabbing the result.template.innerHTML for use later. It works in Chrome and Firefox but in IE11 it returns an empty string.

**Comment by EisenbergEffect** [comment]
`HTMLTemplateElement` has a `content` property that you should access. It may be that innerHTML works on some platforms as well. IE needs a polyfill to work, so perhaps it doesn't entirely fill the API but I haven't seen innerHTML used on the template element in the past. You should be safe in using the `content` property though.
