### ISSUE TITLE
use custom instance of System instead of global.System 

### ISSUE THREAD

**Issue by genadis** [aurelia/loader-default#28]
The loader-default uses `if (!PLATFORM.global.System || !PLATFORM.global.System.import)`, it would be great if we could configure it to use custom System instance instead of global.
So loader-default could be used for the use case below, instead of creating entirely new loader.

I'll be happy to do a PR, but need some guidance on how to best approach it.
 
#### Background
I'm working on widget which is aurelia app for third party websites, so I'm not able to use the global.System, because the System.config is different (in case the website uses Systemjs).

I was thinking of creating new instance of System as mentioned here [System.constructor](https://github.com/systemjs/systemjs/blob/master/docs/system-api.md#systemconstructor) and configure  it for the widget.

Eventually The widget application would be as @EisenbergEffect explained [here](https://github.com/aurelia/framework/issues/235) encapsulated under custom element, using `@noView` and `@processContent(false)`.

I'm working on widget-loader, that will, create the System instance, configure it, add the custom element if needed and bootstrap the aurelia widget application inside some container on the webpage.
I'll make it public when the code is reasonable. 

##### Any advise if I'm missing something or there is better approach would be greatly appreciated!

**Comment by EisenbergEffect** [comment]
We can enable this...I'm just hesitant because I don't know how this relates to the actual loader specification. On this issue, it was a big in flux last I checked. I haven't looked in a bit though.

**Comment by genadis** [comment]
II've done a little research regarding loader spec.

[SystemJS](https://github.com/systemjs/systemjs) is based on [es6-module-loader](https://github.com/ModuleLoader/es6-module-loader) which in turn based on original [API at 2014-08-24 ES6 Specification Draft Rev 27, Section 15](http://wiki.ecmascript.org/doku.php?id=harmony:specification_drafts#august_24_2014_draft_rev_27).
The loader object and constructor is defined there (15.2.3, 26.2).

The new [es6-module-loader 1.0](https://github.com/ModuleLoader/es6-module-loader/tree/1.0) is based on the [new spec](http://whatwg.github.io/loader/) (removed from the ecma spec to separate one).
From what I can tell, [loader contructor](https://whatwg.github.io/loader/#loader-constructor) is still there, and [multiple instances of the loader](https://whatwg.github.io/loader/#loader-internal-slots) are defined. Each loader has private [Registry](https://whatwg.github.io/loader/#registry) that contains map of modules.

The new 1.0 implementation seems very young, but seems like the [constructor](https://github.com/ModuleLoader/es6-module-loader/blob/1.0/src/wrapper-end.js#L7) for [SystemLoader](https://github.com/ModuleLoader/es6-module-loader/blob/1.0/src/system.js#L83) eventually creating instance of [Loader](https://github.com/ModuleLoader/es6-module-loader/blob/1.0/src/loader.js#L12) is already there.

**Comment by EisenbergEffect** [comment]
For now, I would consider creating a custom Loader implementation. That is a supported hook that would let you do whatever you wish.
