### ISSUE TITLE
Firefox: System is not defined.

### ISSUE THREAD

**Issue by bhatnagar-ankur** [aurelia/loader-default#29]
Hi,
I am using Firefox version 42.
The application is not loading and throwing error(ReferenceError: System is not defined), below is the snapshot. I am not sure whether it is a known issue or not.
Please let me know the resolution for it, if any.
![errorfirefoxloading](https://cloud.githubusercontent.com/assets/2298169/11364108/200c230e-92c4-11e5-8e19-6d8a07981ae4.PNG)

Thanks

**Comment by EisenbergEffect** [comment]
The line where the reference error is being thrown does not exist inside of the Aurelia codebase, as far as I can tell. Are you using bundling? Did you reference the System loader? What plugins do you have? We need more information.

**Comment by bhatnagar-ankur** [comment]
I have identified the issue, URL was not getting formed properly on the initial load. It was a hosting issue.
