### ISSUE TITLE
possible issue loading html-only components

### ISSUE THREAD

**Issue by Thanood** [aurelia/loader-default#33]
Hi all,

some users of our plugin complained about it failing to load since the recent update to beta-1.2.0. We could track it down to html-only plugins not being loaded by the text-plugin. SystemJS instead looked for a file named (f.i.) ```md-colors.html.js``` and couldn't find it (```md-colors.html``` is the component and this file is present).

We could resolve that by appending ```!text``` to the globalResources entry:
```javascript
  useColors() : ConfigBuilder {
    this.globalResources.push('./colors/md-colors.html!text');
    return this;
  }
```

[source](https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/blob/master/src/config-builder.js#L115)

Is this intentional with the more strict SystemJS loader or is it a bug?
If it's intentional: I guess this would have side effects to webpack integration since you cannot use this expression in both "worlds", right? We would essentially be dependent on SystemJS.

Thanks in advance :smile: 
(btw: this worked before the update)

**Comment by EisenbergEffect** [comment]
@ahmedshuhel This is a regression. I believe the code we added to handle jspm 0.17 is to "loose" in the way it checks for file extensions. It's breaking on html components. We do need to get this fixed immediately. Do you have time to address it today so I can push out a patch?

**Comment by adriatic** [comment]
#### Congrats to @Thanood 
(he found this issue at the same time we discussed the proper definition of the relative path earlier today)

**Comment by ahmedshuhel** [comment]
I should be able to fix it today.

**Comment by ahmedshuhel** [comment]
@Thanood  Was it like this previously? I mean with out `!text`
```javascript
  useColors() : ConfigBuilder {
    this.globalResources.push('./colors/md-colors.html');
    return this;
  }
```

**Comment by EisenbergEffect** [comment]
@ahmedshuhel Yes, that should work without !test. So, should anything other than .ts or .js actually because the view engine lets plugins be added based on file extension and then it takes care of applying the loader plugin correctly.

**Comment by Thanood** [comment]
@ahmedshuhel yes, it was exactly like that.

**Comment by ahmedshuhel** [comment]
@Thanood Could you test your project with this version of framework I have attached here? 

- Extract and copy `aurelia-framework.js` to `jspm_packages/npm/aurelia-frework@version/aurelia-framework.js`
- Run the application as usual.

> You need to remove `!text` from the module path and go back to how it was previously.

Thanks.



[aurelia-framework.zip](https://github.com/aurelia/loader-default/files/189686/aurelia-framework.zip)

**Comment by Thanood** [comment]
@ahmedshuhel Unfortunately, it's still the same..

```
Unhandled rejection Error: XHR error (404 Not Found) loading http://localhost:3000/src/aurelia-materialize-bridge/colors/md-colors.html.js
```

I'm not sure if the full stacktrace helps. It's quite long so I've put it in a gist:
https://gist.github.com/Thanood/69569d734716fb8bbe61

**Comment by ahmedshuhel** [comment]
@Thanood Thanks for trying. Are you sure you disabled the browser cache? How can I setup the application you are using on my local machine. Is it on github?

**Comment by ahmedshuhel** [comment]
I think it's [demo-materialize](https://github.com/aurelia-ui-toolkits/demo-materialize), right? OK, I will let you know how it goes.

**Comment by Thanood** [comment]
Yes and yes. :smile: 
I disabled the cache - it's disabled when I open dev tools in Chrome.

The project is on GitHub:
https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge

**Comment by Thanood** [comment]
Well, you're right actually, demo-materialize is quite the same and easier to setup. But it's not updated to beta-1.2.0 yet.

**Comment by Thanood** [comment]
@ahmedshuhel Here is a copy of the current skeleton-navigation with a feature folder in ```src/features```, reproducing this issue.

**Comment by ahmedshuhel** [comment]
You probably missed the link.

**Comment by Thanood** [comment]
I did miss it at first but now I see the link in my post.
Anyway, here it is: https://github.com/Thanood/aurelia-html-component-issue

**Comment by ahmedshuhel** [comment]
Sorry, got it. I had to refresh the browser.

**Comment by ahmedshuhel** [comment]
Strange! This is almost exactly how I tested with [this app](https://github.com/ahmedshuhel/aurelia-feature) and it worked. Take a look at [this line here](https://github.com/ahmedshuhel/aurelia-feature/blob/master/src/features/well/index.ts#L2)

**Comment by Thanood** [comment]
When I ```jspm install``` it, that app loads pre-beta-1.2.0 Aurelia packages.
I'm afraid I have to leave now but I will take a look at it later again.

**Comment by Thanood** [comment]
After jspm update, it doesn't work anymore. :smile:

**Comment by ahmedshuhel** [comment]
No problem. jspm update? What is the SystemJS version you have after you do `jspm update`? Are you using the file/module I have attached above?

**Comment by Thanood** [comment]
I took your repo as it is, so it's not using the file from above.
SystemJS is at v0.19.18

Having replaced ```aurelia-framework.js``` now with the file provided. The error is still the same.

**Comment by ahmedshuhel** [comment]
I may have uploaded a wrong file. Give me a sec.

**Comment by ahmedshuhel** [comment]
[aurelia-framework.zip](https://github.com/aurelia/loader-default/files/190474/aurelia-framework.zip)

Please give it another try with the file above.

**Comment by ahmedshuhel** [comment]
I have tested https://github.com/Thanood/aurelia-html-component-issue and working on my machine.

**Comment by Thanood** [comment]
Good news!

```
My brand new feature is live and kicking!
Feature 2 is live and kicking too!
INFO [aurelia] Aurelia Started
```

:smile:

**Comment by ahmedshuhel** [comment]
:)

**Comment by Thanood** [comment]
The au-well is also there, of course.

**Comment by ahmedshuhel** [comment]
@EisenbergEffect We believe [the PR](https://github.com/aurelia/framework/pull/383) is good to go.

**Comment by Thanood** [comment]
Solved in the recent release. :+1:
