### ISSUE TITLE
Support for Webpack

### ISSUE THREAD

**Issue by Vaccano** [aurelia/loader-default#35]
Does this support webpack?  I see code for other loaders in here, but I have not seen anything webpack specific.  

Maybe it does not need anything here?  If so, it would be nice to know. 

Basically I run the following in my `main.ts` and I worry it will not work with webpack:

    // Setup view -> viewModel relationship to support value-view.htm and value-vm.ts
    ViewLocator.prototype.convertOriginToViewUrl = (origin) => {
        let moduleId = origin.moduleId;
                
        // remove the file extension
        moduleId = moduleId.substring(0, moduleId.lastIndexOf('.'));
                
        // see if the module ends in 'Vm'
        if (moduleId.endsWith('-vm')) {
            var coreName = moduleId.substring(0, moduleId.length - 3);
            return coreName + '-view.html';
        }
        else {
            return moduleId + '.html';
        }
    };

**Comment by EisenbergEffect** [comment]
There's a special loader for webpack called loader-webpack. You can check out that implementation and see if it will work for your scenarios. If there are issues, definitely consider submitting PRs.

**Comment by EisenbergEffect** [comment]
I think this should work though. It's very like the default implementation.

**Comment by Vaccano** [comment]
@EisenbergEffect OK. I will look at loader-webpack.  Thanks for the response!
