### ISSUE TITLE
Cannot set SystemJS.map["aurelia-framework"] directly.

### ISSUE THREAD

**Issue by MrChriZ** [aurelia/loader-default#39]
Note this is an issue specfically when using  JSPM 0.17/SystemJS 0.20.

**I'm submitting a bug report**

* **Library Version:**
V1.0.0

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
6.9.4

* **NPM Version:**
3.8.9

* **JSPM OR Webpack AND Version**
**"jspm": "^0.17.0-beta.38"**

* **Browser:**
Chrome XX 

* **Language:**
all

**Current behavior:**
Aurelia fails to load with a message:
bluebird.min.js:29 Unhandled rejection Error: Cannot set SystemJS.map["aurelia-framework"] directly. Use SystemJS.config({ map: { "aurelia-framework": ... } }) rather.
    at Object.set (https://localhost:9002/jspm_packages/system.js:5:13228)
    at DefaultLoader.map (https://localhost:9002/jspm_packages/npm/aurelia-loader-default@1.0.0/aurelia-loader-default.js:228:22)

**What's the problem.:**
Not working with JSPM 0.17/SystemJS 0.20
I think this is a compatability issue with aurelia-loader-default using system.map.

**Comment by EisenbergEffect** [comment]
Already fixed in master. This was a breaking change in SystemJS.

**Comment by MrChriZ** [comment]
Great thanks.
