### ISSUE TITLE
define is undefined

### ISSUE THREAD

**Issue by davismj** [aurelia/loader-default#42]
**I'm submitting a bug report**

* **Library Version:**
1.0.2

* **Operating System:**
all

* **Node Version:**
7.7.0

* **NPM Version:**
4.4.2

* **JSPM OR Webpack AND Version**
JSPM 0.16.53

* **Browser:**
all (Chrome)

* **Language:**
TypeScript

**Current behavior:**
Right now, when bundling a jspm sfx, this line throws an error that define is not defined.
https://github.com/aurelia/loader-default/blob/eb18cd43fae48125f73f14548e1125952605f678/src/index.js#L169

* **What is the expected behavior?**
Perhaps there might be some way to handle this other than assuming define is defined?

* **What is the motivation / use case for changing the behavior?**
For self-contained bundles, such as JSPM sfx bundles.

**Comment by EisenbergEffect** [comment]
We've never supported jspm sfx as far as I know. This would be a new feature and I'm not sure how easy/hard it is add.

**Comment by ahmedshuhel** [comment]
Will look into it.

**Comment by michaelbull** [comment]
I'm also hitting this issue when attempting to using [`karma-typescript`](https://www.npmjs.com/package/karma-typescript) and attempting to [import `aurelia-loader-default`](https://github.com/michaelbull/aurelia-typescript-webpack-starter/blob/karma/test/karma-setup.ts#L1) in my spec-bundle. The full stack trace is:

```
Uncaught (in promise) ReferenceError: define is not defined
    at DefaultLoader.addPlugin (karma-typescript-bundle-9121PAwdWrQ9hr4V.js:2307)
    at new DefaultLoader (karma-typescript-bundle-9121PAwdWrQ9hr4V.js:2212)
    at createLoader (karma-typescript-bundle-9121PAwdWrQ9hr4V.js:655)
    at <anonymous>
```

And the line 2 of the following block of code is producing it:

```js
  DefaultLoader.prototype.addPlugin = function (pluginName, implementation) {
    var nonAnonDefine = define;
    nonAnonDefine(pluginName, [], {
      'load': function load(name, req, onload) {
        var result = implementation.fetch(name);
        Promise.resolve(result).then(onload);
      }
    });
```

Which aligns with the issue described in the first post of this thread.

**Comment by EisenbergEffect** [comment]
Closing this as something we're not going to do now that we have the CLI.
