### ISSUE TITLE
TypeError on IE, System.registry.entries() not defined in case of undefined Symbol or Symbol.iterator

### ISSUE THREAD

**Issue by reinholdk** [aurelia/loader-default#43]
**I'm submitting a bug report**

* **Library Version:**
1.0.2

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
7.8.0

* **NPM Version:**
4.0.5

* **JSPM OR Webpack AND Version**
JSPM 0.17.0-beta.41

* **Browser:**
IE 11 

* **Language:**
ESNext

**Current behavior:**
A type error occurs on IE11: Object doesn't support property or method 'entries'
https://github.com/aurelia/loader-default/blob/31f848d491c7edba244826b5c077dc1fe7445f29/src/index.js#L180

**Expected/desired behavior:**

* **What is the expected behavior?**
Do not use Object.entries() or provide a polyfill in aurelia-polyfills 

* **What is the motivation / use case for changing the behavior?**
Do not require external polyfills when using aurelia libraries.

**Comment by StrahilKazlachev** [comment]
You have this wrong. This is *not* `Object.entries`, it's `Map.prototype.entries`. `System.registry` is a `Map`.

**Comment by reinholdk** [comment]
It is not really a Map:

https://github.com/ModuleLoader/es-module-loader/blob/31a72a20e500fa179ad590aac82a00415847c0dd/core/loader-polyfill.js#L126-L154

**Comment by StrahilKazlachev** [comment]
Then we should be able to just use `for` instead of `for of`.
Now I'm more curious about the `Error`, `System.registry.entries` should be there regardless of polyfills. And I don't see any other `.entries` in the transpiled code.

**Comment by StrahilKazlachev** [comment]
OK, so `Registry.prototype.entries` is only available if there is an iterator support - we should do with `.keys` and `.values` only.

**Comment by reinholdk** [comment]
Exactly, ```typeof Symbol``` is undefined at the time SystemJS is loaded, i.e. ```System.registry.entries``` does not get defined on IE.

**Comment by StrahilKazlachev** [comment]
@reinholdk Do you mind editing the title and content to reflect that this is not an issue with `Object.entries`, but with `Symbol` and `Symbol.iterator`.
