### ISSUE TITLE
[BUG] dist/commonjs/aurelia-loader-default.js is syntactically broken for using in requirejs

### ISSUE THREAD

**Issue by huochunpeng** [aurelia/loader-default#47]
**I'm submitting a bug report**

* **Library Version:**
1.0.3

**Please tell us about your environment:**
* **Operating System:**
N/A

* **Node Version:**
N/A

* **NPM Version:**
N/A

* **JSPM OR Webpack AND Version**
N/A

* **Browser:**
all

* **Language:**
all

**Current behavior:**
Current `dist/commonjs/aurelia-loader-default.js` would not work. But all aurelia apps with jspm/requirejs/webpack (well, webpack does not use this package) are NOT affected because every apps use `dist/amd` build.

In the mulfunctional commonjs build, there are two type of usage of `require`
1. commonjs require call
https://github.com/aurelia/loader-default/blob/a6af5723974028d9d4b9254a0fc65946356fdb15/dist/commonjs/aurelia-loader-default.js#L8

2. amd require call
https://github.com/aurelia/loader-default/blob/a6af5723974028d9d4b9254a0fc65946356fdb15/dist/commonjs/aurelia-loader-default.js#L132

This is syntactically wrong, because no JavaScript interpreter can distinguish the two types of `require` call. Because the two are same identifier in same JS function scope, they are guaranteed being treated as same thing.

The result is there is no way to use this commonjs build in requirejs based app. It would not work after wrapping it into AMD code.

I have no idea how to fix this edge case, but to enforce using `dist/amd` on `aurelia-loader-default` for requirejs based app.
In case you wonder what I am doing here, I am trying to simplify aurelia-cli without consulting jspm section of package.json.

**Expected/desired behavior:**

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

**Comment by huochunpeng** [comment]
Damn, just realized there is a simple fix, just use `requirejs([])` instead of `require([])`. PR coming.

**Comment by Alexander-Taran** [comment]
Leave a problem be.. it might solve itself (-:
@huochunpeng you are awesome
