### ISSUE TITLE
Can not seperate *.js modules in a module folder and .html files in a views folder

### ISSUE THREAD

**Issue by bastienJS** [aurelia/loader-default#5]
I wanted to put ALL my .js modules into a ./modules folder.
I wanted to put ALL my .html files into a ./views folder.

Doing this I get errors from the ES6 module loader that he can not find files in the ./dist folder.

Then I asked in aurelia gitter @Aaike
https://gitter.im/Aurelia/Discuss?at=55619a953715cd9539a956df

This is what I tried with no luck. It seems I can not put the app.js in the ./modules folder because it expects the app.html also there - What I do not want -

This is what we tried and some more settings which I do not have anymore.

Please update your documentation with this basic feature everyone wants to use seperation of concern :-)

```

System.config({
  "transpiler": "babel",
  "baseViewUrl": "dist/views", //<--- TELL WHERE TO FIND HTML FILES
  "paths": {
    "*":dist/modules/*.js", //<--- TELL WHERE TO FIND JS FILES
    "github:*": "jspm_packages/github/*.js",
    "npm:*": "jspm_packages/npm/*.js",
  }
});

```

```
System.config({
  "transpiler": "babel",
  "baseUrl": "dist/modules",//<--- TELL WHERE TO FIND JS FILES
  "baseViewUrl": "dist/views", //<--- TELL WHERE TO FIND HTML FILES
  "paths": {
    "*":*.js", 
    "github:*": "jspm_packages/github/*.js",
    "npm:*": "jspm_packages/npm/*.js",
  }
});
```

**Comment by EisenbergEffect** [comment]
The code you are showing here looks to be based on a very old version of the loader. We no longer use baseViewUrl or baseUrl (which was actually a typo on our part and a misunderstanding of SystemJS). Have you looked into customizing the ConventionalViewStrategy? Have a look at this: http://aurelia.io/docs.html#view-and-view-model-conventions  It's likely that you will need some combination of SystemJS config and our view strategy customization. Probably configuring the SystemJS * path as above, plus the custom convention mapping.

**Comment by bastienJS** [comment]
No I haven`t Aaike threw the baseViewUrl at me and I said it might be outdated :P but I gave it a go... Thanks for the ConventionalViewStrategy hint, I try that.

**Comment by shanonvl** [comment]
@bastienJS, as @EisenbergEffect says, you can customize the ConventionalViewStrategy, however I'm going a different route which also fixes the problem:

```
── ui
│   ├── index.js
│   ├── layout
│   │   ├── border-layout
│   │   │   ├── border-layout.scss
│   │   │   ├── index.html
│   │   │   ├── index.js
│   │   │   ├── region.html
│   │   │   └── region.js
│   │   └── index.js
│   ├── page
│   │   ├── dashboard
│   │   │   ├── dashboard.scss
│   │   │   ├── default.html
│   │   │   ├── default.js
│   │   │   ├── index.html
│   │   │   └── index.js
│   │   ├── editor
│   │   │   ├── editor-sheet
│   │   │   │   ├── index.html
│   │   │   │   └── index.js
│   │   │   ├── editor.scss
│   │   │   ├── index.html
│   │   │   └── index.js
│   │   └── index.js
│   └── widget
│       ├── blank
│       │   ├── index.html
│       │   └── index.js
│       ├── chart
│       │   ├── chart.scss
│       │   ├── index.html
│       │   └── index.js
│       ├── common
│       │   ├── footer
│       │   │   ├── index.html
│       │   │   └── index.js
│       │   └── header
│       │       ├── header.scss
│       │       ├── index.html
│       │       └── index.js
│       ├── data-table
│       │   ├── index.html
│       │   └── index.js
│       ├── index.js
│       ├── inspector
│       │   ├── index.html
│       │   ├── index.js
│       │   └── inspector.scss
```

`ui` is just under `src`.   The `index.js` at each level includes the appropriate resources/widgets/etc and I'm using custom elements whenever possible.

This enables great organization, keeping everything grouped by module js/html/css.

**Comment by bastienJS** [comment]
@shanonvl  Actually your solution design is what I prefer. How did you make that structure work, when all files are not anymore in the root /dist folder? I get errors like localhost:9000/dist/mymodule.js (404)

**Comment by jdanyow** [comment]
@bastienJS can this be closed?
