### ISSUE TITLE
Templates loading

### ISSUE THREAD

**Issue by Mordred** [aurelia/loader-default#6]
Hi, after today Aurelia update, my project stop working:

![image](https://cloud.githubusercontent.com/assets/29232/8052996/d1507b18-0e8c-11e5-9d85-8f0a719b7a7b.png)

I'm trying to do more research, but without any luck.

**Comment by zewa666** [comment]
Sounds like you haven't updated that repo properly with jspm. I've just downloaded a fresh copy of the new skelly and it works. So it must be something regarding to updating

**Comment by Mordred** [comment]
You were right. Some packages were installing old version. I have to override their dependencies using `-o`.

`aurelia-computed`, `aurelia-validtion` and `aurelia-compiler`

**Comment by danielheddelin** [comment]
@Mordred You ran jspm install aurelia-computed -o and the same with validation, which solved the problem for you? aurelia-compiler isn't part of the skelly. Would you mind pasting your package.config jspm-section?

**Comment by Mordred** [comment]
Until this packages will be up to date with Aurelia, you can override their dependencies with inside `package.json`:

```json
{
    "jspm": {
        ...
        "overrides": {
            "github:aurelia/validation@0.2.4": {
                "dependencies": {
                    "aurelia-binding": "github:aurelia/binding@^0.7.0",
                    "aurelia-dependency-injection": "github:aurelia/dependency-injection@^0.8.0",
                    "aurelia-templating": "github:aurelia/templating@^0.12.0"
                }
            },
            "github:jdanyow/aurelia-computed@0.1.1": {
                "dependencies": {
                    "aurelia-binding": "github:aurelia/binding@^0.7.0",
                    "aurelia-logging": "github:aurelia/logging@^0.5.0",
                    "core-js": "npm:core-js@^0.9.5"
                }
            },
            "github:aurelia/validation@0.2.4": {
                "dependencies": {
                    "aurelia-binding": "github:aurelia/binding@^0.7.0",
                    "aurelia-dependency-injection": "github:aurelia/dependency-injection@^0.8.0",
                    "aurelia-templating": "github:aurelia/templating@^0.12.0"
                }
            }
        }
        ...
    }
}
```

**Comment by flieks** [comment]
@Mordred you put 2 times github:aurelia/validation@0.2.4 in your overrides. What is your real 3th override?

**Comment by flieks** [comment]
you are referencing the latest versions in your overrides..
i deleted couple of times the aurelia jspm packages (and config).
i pasted the overrides in the package.json.
i did 
jspm install aurelia-computed -o
jspm install aurelia-validation -o

then i get this in package.json (at bottom)
```
    "overrides": {
      "github:aurelia/validation@0.2.4": 2,
      "github:jdanyow/aurelia-computed@0.1.1": 2
    }
```

still have same error's as you (in chrome)

**Comment by Mordred** [comment]
`-o` is option which requires some additional data: JSON or file.

`jspm install aurelia-computed -o "...JSON string..."`

If you still have errors, check if you haven't some other dependency problem.

Can you write what is your `jspm install` output?

**Comment by flieks** [comment]
@Mordred here is the jspm output , package.json and config.js
[gist](https://gist.github.com/flieks/c407eab5d2164cecfc2e)

**Comment by flieks** [comment]
info of jspm inspect (and --fork) [gist](https://gist.github.com/flieks/79b912daf9e0e17fdcf8)

**Comment by Mordred** [comment]
Try to override `aurelia-breeze` dependencies.

This is the problem:
```
     Installed Forks
 
                     github:aurelia/binding 0.6.1 0.7.0
        github:aurelia/dependency-injection 0.7.1 0.8.1
                 github:aurelia/http-client 0.8.1 0.9.1
                     github:aurelia/logging 0.4.0 0.5.0
                    github:aurelia/metadata 0.5.0 0.6.0
                        github:aurelia/path 0.6.1 0.7.0
                  github:aurelia/task-queue 0.4.0 0.5.0
              github:pwkad/aurelia-bs-modal master 0.1.2
```

Try to solve all dependencies, so you don't have forks of aurelia packages.

**Comment by flieks** [comment]
that was a great idea @Mordred , unfortunately it didn't work. 
But then @jdanyow came with a breeze plugin update which fixed the issue. 

Thanks
