### ISSUE TITLE
error loading bundled templates

### ISSUE THREAD

**Issue by olanod** [aurelia/loader-default#8]
As pointed [here on gitter](https://gitter.im/Aurelia/Discuss?at=55b961fe4c04f0cc22e74239), when I try to load templates from a html bundle It fails because the loader looks for a view with an absolute url in the bundle file but the templates ids are relative module ids.

**Comment by EisenbergEffect** [comment]
Are you using the jspm beta? If so, I'm wondering if this is something that changed...and broke our stuff. @ahmedshuhel You may need to look into this. I'm not sure if we need to change the bundling or the loader.

**Comment by ahmedshuhel** [comment]
@olanod Could you please raise the issue on aurelia/cli repo? And please share your aureliafile and config,js too.

**Comment by olanod** [comment]
It's magically solved! Nothing like deleting everything and installing again.  
I do have a very customized bundling process though, with a custom version of aurelia-cli(maybe I can submit some PRs) and it looks something like this using gulp:
```
var aureliaBundle = require('aurelia-cli').bundle; // I exposed the bundle function
...
gulp.task('bundle', function(done) {
    aureliaBundle({
        js: {
            'dist/bundle': {
                modules: [
                    'myapp/**/*',  // 
                    'aurelia-bootstrapper',
                    'github:aurelia/history-browser@0.6.2',
                    'github:aurelia/loader-default@0.9.1',
                    'github:aurelia/templating-binding@0.13.2',
                    'github:aurelia/templating-resources@0.13.3',
                    'github:aurelia/templating-router@0.14.1'
                ],
                options: { inject: false, sourcemaps: false, minify: true }
            }
        },
        template: {
            'dist/bundle': {
                pattern: 'app/**/*.html',
                options: { inject: false }
            }
        }
    }, {
        force: true,
        baseURL: 'dist' // my index.html and config.js are in a sub-directory(src) and dist files in ... dist
    }).then(function() { // bundle returns a promise
        console.log('bundle finished!');
        done();
    });
});
```

**Comment by EisenbergEffect** [comment]
Hmm. I talked with Guy and there probably is an issue with the jspm beta...so that may have been your cause.

**Comment by olanod** [comment]
Probably yes. One of the many things I did was downgrading my global installation of jspm
